from setuptools import setup, find_packages

setup(
    name="dit_edit",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "torch>=2.4.0",
        "gradio>=4.44.1",
        "pip>=24.0.1",
        "pillow",
        "numpy",
        "pandas",
        "tqdm",
        "diffusers",
        "transformers",
        "einops",
        "accelerate",
        "scikit-image",
        "lpips",
        "rembg",
        "matplotlib",
        "sentencepiece",
        "jupyter",
        "ipykernel",
        "scipy",
        "seaborn",
        "hpsv2",
        "rembg",
    ],
    python_requires=">=3.10",
)